"""Precomputed-spine adapter.

Some corpora store each trajectory's atom sequence directly, as one
space-joined string called a spine (e.g. ``"think edit run_test submit"``).
The `midah/procgrep-spines <https://huggingface.co/datasets/midah/procgrep-spines>`_
store regenerated by ``analysis/build_spines.py`` uses this format. The
adapter splits the string on whitespace; the tokens pass through as-is,
since a spine is already canonical atoms.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from procgrep.canonicalize import register_adapter
from procgrep.types import AtomSequence

SPINE_FIELD = "spine"


def spine_adapter(record: Mapping[str, Any]) -> AtomSequence:
    """Split a record's space-joined ``spine`` string into atoms."""
    value = record.get(SPINE_FIELD)
    if not isinstance(value, str):
        return []
    return value.split()


def _register() -> None:
    register_adapter("spine", spine_adapter, overwrite=True)


_register()


__all__ = ["SPINE_FIELD", "spine_adapter"]
